spring.application.name=schoolmanager
server.port=${PORT:8080}
server.address=0.0.0.0
spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=school_management_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Dangcongvu2005@
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false