app.datasource.online.jdbc-url=jdbc:sqlserver://den1.mssql8.gear.host:1433;databaseName=dbtest2026;encrypt=true;trustServerCertificate=true
app.datasource.online.username=dbtest2026
app.datasource.online.password=Bk8G_wzh0?I1
app.datasource.online.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
