app.datasource.local.jdbc-url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=school_management_db;encrypt=true;trustServerCertificate=true
app.datasource.local.username=sa
app.datasource.local.password=Dangcongvu2005@
app.datasource.local.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
